### ISSUE TITLE
JSON, possibly others, no longer work with macOS Catalina (10.15)

### ISSUE THREAD

**Issue by r3volution11** [sindresorhus/quick-look-plugins#104] opened 2019-07-07 05:33 UTC
I recently noticed that the JSON plugin no longer works correctly. It gives a warning that the file can not be previewed safely. See below:

![Screen-Shot-2019-07-07-01-31-56 34](https://user-images.githubusercontent.com/698508/60764414-27b0ae00-a057-11e9-88ea-323b257888ba.png)

**Comment by sindresorhus** [comment] 2019-07-07 13:35
Duplicate of #103

**Closed by sindresorhus** 2019-07-07 13:35 UTC
