### ISSUE TITLE
Mac Catalina breaks everything

### ISSUE THREAD

**Issue by NylonDiamond** [sindresorhus/quick-look-plugins#113] opened 2019-10-09 06:02 UTC
I upgraded to Mac Catalina and all my quick look previews are defaulting to their original mac previews. I place plugins in the correct location but they don't trigger in preview mode.

**Comment by sindresorhus** [comment] 2019-10-09 09:41
Duplicate of #112

**Closed by sindresorhus** 2019-10-09 09:41 UTC
